### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#195]
Add an about page. Explain the project, federated metadata, roadmapping, etc...

* The kinds of resources here and how they're different
* Clarify this is not all maps at PUL
* The data sets you can find on this site are part of a larger set of tools for doing GIS research.
  * how to use this site and the resources you find here

**Comment by tpendragon** [comment]
We're going to draft some text, give it to Kim to approve (in a PR), and then merge it.

**Comment by sdellis** [comment]
__First (incomplete) Draft:__

# About the Digital Map and Geospatial Data Portal

The Princeton University Library’s Digital Maps and Geospatial Data website allows researchers to discover and access online maps and geospatial data in the Princeton Maps Collection, one of the largest cartographic collections at any academic institution.

## Types of Maps found in the Portal

### Sanborn Maps

(Something about Sanborn here since they don’t fall into the other categories.)

[Example Sanborn Map Here.]

### Scanned Maps

Scanned Maps are print maps that have been digitized and combined with geographic information, allowing for accurate positioning of the map on an interactive, modern globe. Many of the Scanned Maps available in the Digital Map and Geospatial Data Portal are historic, allowing researchers to compare past geographic boundaries and names with their modern counterparts. Princeton University Library has a strong commitment to scanning our print maps collection, so scanned maps are added to the portal on a regular basis.

[Example Scanned Map Here.]

### Vector Data

Vector graphics are stored via mathematical calculations from one point to another that form smooth lines and shapes. They can be resized to any dimension without losing clarity. Vector Data is spatially referenced data which is represented by three types of marks: point, line (or arc), and polygon data. 

- **Point Data** is most commonly used to represent non-adjacent features and to represent discrete data points. Examples would be bus stops, schools, city names, and other points of interest. 
- **Line Data** is ...
- **Polygon Data** is ... 

[Example Images of the three above Vector data types.]

### Raster Data 
Raster images are made of tiny squares called pixels. Raster data (also known as grid data) represents “surfaces”.  Raster data is grid-based, often by pixel, and each unit expresses a data value that is represented visually. Raster Data often includes topographies as well as aerial and satellite imagery. There are two types of raster data: continuous and discrete.  An example of discrete raster data is population density.  Continuous data examples are temperature and elevation measurements. There are also three types of raster datasets: thematic data, spectral data, and pictures (imagery).

- **Thematic Data** can be used for Digital Elevation Model (DEM). Each cell represents a 30m pixel size with an elevation value assigned to that cell. 
- **Spectral Data** can be used for spatial hydrology modeling such as extracting watersheds and flow lines in a geographic area. Spectral data is often used in aerial or satellite imagery which, for example, can be used to derive vegetation geologic information by classifying the spectral signatures of each type of feature.
- **Image** Aerial and satellite imagery is one type of raster data. Raster Image file types include BMP, TIFF, GIF, and JPEG.

[Example Image for each of the Raster data types here.]

Raster images accompanied by a second file known as a world file. The world file has the same name as the raster image file but has a different extension. The world file is a text file that contains the map projection information needed to properly georeference the raster image.

## Subject Areas
The maps and data in this collection may be used for many areas of scholarship, but highlights include: 
- Geology
- Geochemistry
- Geophysics
- Climatology
- Natural Resources 
- Land Use
- Soils
- Water Resources
- Remote Sensing
- Topography
- Political and Cultural Geography
- Physiography
- Bathymetry
- Transportation
- Navigation
- Urban and Regional Planning
- Public Policy

## Research Support
If you need help in finding or locating the data you are looking for, contact Tsering Wangyal Shawa, GIS and Map Librarian.

**Comment by hackartisan** [comment]
I'm not the most qualified to review for technical accuracy but I think the draft looks nice!
