### ISSUE TITLE
Map markers should be interactive

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#358]
Clicking on map markers should take user to the document it represents in the search results. For an example, see the map marker behavior in Foursquare.

**Comment by sdellis** [comment]
There is a problem when interacting with records that are further down the document list. They don't always scroll to the top because of the length of the page. If we are using Foursquare for inspiration, we need to at least highlight the record as well. It would also be nice to provide a pop up representation of the record directly over the marker. I will make these updates in a new branch.

**Comment by eliotjordan** [comment]
I'm not sold on the popup. I think that it is overkill. We already have the search results directly adjacent to the map. Highlighting seems like a good idea.
