### ISSUE TITLE
Change geocoder plugin

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#486]
Mapzen is shutting down, so we need to replace the geocoder plugin that uses it's search API.

https://mapzen.com/blog/shutdown/

**Comment by jrgriffiniii** [comment]
After discussing this further on 01/23/18, it was decided that addressing this immediately by supporting ES6 integration without Webpacker is the wisest approach

**Comment by jrgriffiniii** [comment]
Given that [GeoBlacklight](https://github.com/geoblacklight/geoblacklight) shall plan to support integration with JavaScript using Webpacker (pending the completion and merging of https://github.com/projectblacklight/blacklight/pull/1727), ES6 transpiling in order to deprecate [mapzen/leaflet-geocoder](https://github.com/mapzen/leaflet-geocoder) can be provided using Webpacker.  This approach was identified during the GeoBlacklight Winter 2018 checkin for 01/23/18.

**Comment by jrgriffiniii** [comment]
https://github.com/rails/webpacker/issues/357#issuecomment-300400010 was blocking builds on Travis CI
