### ISSUE TITLE
[Pulmap/production] ActiveSupport::MessageVerifier::InvalidSignature: ActiveSupport::MessageVerifier::InvalidSignature

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#949]
This error started happening on June 5th. 

Should we handle this exception so that we don't add noise to Honeybadger? 

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/79805504)

**Comment by bess** [comment]
If this were being rescued, I'd expect these notices to have stopped after PR #963 was deployed, but they have not stopped. I wonder if it's because the path (`/rails/active_storage/representations... etc`) is not going through the application controller somehow? 

![Screen Shot 2021-08-23 at 9 44 34 AM](https://user-images.githubusercontent.com/65608/130458100-79806859-a4ae-49a6-b16e-988ff97fc6de.png)

Could this be a hacking attempt? Or is there a mis-configured URL linked somewhere?

**Comment by eliotjordan** [comment]
These all appear to be caused by GoogleImageProxy sending a non-valid request for an image. On inspection in the browser, the thumbnails for the records appear without issue. I'm going to suppress this exception in Honeybadger and remove the `rescue_from` handler that doesn't work for ActiveSupport exceptions.

https://github.com/pulibrary/pulmap/blob/main/app/controllers/application_controller.rb#L13
